@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "add n/David"

package States {
    class State1 as """%n()<u>snapshot0</u>"
    class State2 as ""New contact added: John..."%n()<u>snapshot1</u>"
    class State3 as ""Deleted contact: John..."%n()<u>snapshot2</u>"
}


State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "snapshotPosition = 2" #FFFFFF

Pointer -up-> State3
@end
